programs:
  - name: tcprtt
    metrics:
      histograms:
        - name: tcp_rtt_histogram
          description: TCP round trip time histogram
          bucket_type: exp2
          bucket_min: 0
          bucket_max: 27
          labels:
            - name: rtt
              type: u64 # 要求与 bpf 结构体数据类型一致
  - name: tcpretrans
    metrics:
      counters:
        - name: tcp_retrans_counter
          description: The number of TCP retransmissions
          labels:
            - name: saddr
              type: u8[16]
              decoder:
                name: inet # 将 IP 转成字符串
            - name: daddr
              type: u8[16]
              decoder:
                name: inet # 将 IP 转成字符串
            - name: sport
              type: u8
            - name: dport
              type: u8
            - name: protocol
              type: int
              decoder:
                name: static_map
                static_map:
                  2: IPv4
                  10: IPv6
  - name: tcpconnlat
    metrics:
      histograms:
        - name: tcp_connect_latency
          description: Tcp connect latency histograms
          bucket_min: 0
          bucket_max: 27
          bucket_type: exp2
          labels:
            # 观测值放第一个
            - name: delta
              type: u64
  - name: biolatency
    metrics:
      histograms:
        - name: bio_latency_histogram
          description: Block IO latency histogram
          bucket_type: exp2
          bucket_min: 0
          bucket_max: 27
          labels:
            - name: latency
              type: u64
            - name: dev # device
              type: u32
            - name: op # operation
              type: u8
              decoder:
                name: static_map
                static_map:
                  0: read
                  1: write
                  2: flush
                  3: insert

server:
  port: 8089 # 不写默认 8089
