{
 "title": "ecli",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "TCP connect latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tcp_connect_latency_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "TCP RTT",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "tcp_rtt_histogram_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Bio latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "bio_latency_histogram_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "TCP retrans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "tcp_retrans_counter", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}